### ISSUE TITLE
Please, add-on needs to be updated!

### ISSUE THREAD

**Issue by Dino804** [accessifix/nvda-for-vs-code#3]
NVDA is transitioning in version 2019.3 to Python 3.
Older add-on versions which are still in Python 2 no longer supported to install them in NVDA 2019.3 and later.

**Comment by pawelurbanski** [comment]
I will update the add-on to Python 3. The next step will be dealing with widgets that display tooltips for function parameter types or similar cases. I will also browse through the issues related to accessibility, and definitely try to bring up improvements coming from my own experience.
I no longer code that much, but do care alot about the user experience when you use the tool like VS Code for hours.

**Comment by Dino804** [comment]
Many thanks. Here's a following guide which maybe helps.

[A documentation about code porting to Python 3](http://python3porting.com/)

**Comment by alex19EP** [comment]
i think now it is fixed.

**Comment by ghost** [comment]
Hi folks. I rely on VS Code for work and school. Before I update to the latest NVDA version, can I be assured this add on is Python 3 compliant? Thank you to the gracious and kind developer who does this on his own time because he believes in our access to VS Code. Your hard work and selflessness is appreciated!

**Comment by pawelurbanski** [comment]
Yes, it is I am working on some very much needed additional fixes this very moent.
I’m in touch with the VS Code team to organize feedback and do required work in parallel.

Possible current issues as of version 1.42.1:

  *   The VS Code editor gets assigned a name by using aria-label attribute,
  *   It makes NVDA read its name after every completion and it is either a regression from previous versions or a change how NVDA handles the events,
  *   Since the editor area is an HTML textarea its attributes such as: multiline and autocomplete are announced by NVDA, which I plan to silence by renaming the values for the states dictionary to empty strings.



If you could wait for a few days with updates that would be a safe thing to do.

**Comment by pawelurbanski** [comment]
I've updated the add-on. There is no major functionality introduced. I checked it using NVDA 2019.3.1 and the latest VS Code as of this date, namely: 1.42.1.

Please, head on to the releases section to download the updated package and read a few nots about whats new and old.
